# Generated by Django 4.2.5 on 2023-09-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_alter_documento_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default='', upload_to='documentos'),
            preserve_default=False,
        ),
    ]
